### ISSUE TITLE
Demo app not working

### ISSUE THREAD

**Issue by opsidao** [xing/hardcover#8]
The demo app linked in the README (https://damp-shore-4827.herokuapp.com/) is not working, maybe interesting to either remove the link from the README or setting a new demo somewhere.

**Comment by pietbrauer** [comment]
Thanks, will fix that. I changed the URL lately and forgot about the readme. I changed the URL in the top of the repository though. It's now sitting at a more readable URL at https://hardcover-demo.herokuapp.com/

**Comment by opsidao** [comment]
:wink:
